[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.32"
rand = "0.8"
clap = {version = "4", features = ["derive"]}
